# permissions for end users to view runbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: inbox-agent
    app.kubernetes.io/managed-by: kustomize
  name: monitoring-runbook-viewer-role
rules:
- apiGroups:
  - monitoring.appscode.com
  resources:
  - runbooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.appscode.com
  resources:
  - runbooks/status
  verbs:
  - get
