---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monitoring.appscode.com
  resources:
  - runbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.appscode.com
  resources:
  - runbooks/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.appscode.com
  resources:
  - runbooks/status
  verbs:
  - get
  - patch
  - update
